import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const data = (await readFile(new URL('src/data.js', root), 'utf8')).replace(/^export /gm, '');
const app = (await readFile(new URL('src/app.js', root), 'utf8')).replace(/^import .*?;\s*/m, '');
await writeFile(new URL('src/site.js', root), '// Generated by npm run build. Edit data.js and app.js instead.\n(() => {\n"use strict";\n' + data + '\n' + app + '\n})();\n');
console.log('Built src/site.js — supports file:// and HTTP.');
