/** Web app bound to the price spreadsheet (Extensions → Apps Script). */
function doGet(e) {
  var p = (e && e.parameter) || {};
  var callback = p.callback || '';
  // JSONP callback names are generated by the site and never taken verbatim.
  if (callback && !/^__gtsToCallback_[A-Za-z0-9_]+$/.test(callback)) {
    return ContentService.createTextOutput('Invalid callback').setMimeType(ContentService.MimeType.TEXT);
  }
  var result;
  try {
    var db = readDatabase_();
    if (p.action === 'catalog') result = { ok: true, models: db.models };
    else if (p.action === 'quote') {
      var match = db.prices.filter(function(row) {
        return row.modelId === p.modelId && row.type === p.type;
      });
      result = match.length === 1
        ? { ok: true, modelId: match[0].modelId, type: match[0].type,
            priceId: match[0].priceId, price: match[0].price, currency: 'RUB' }
        : { ok: false, error: 'Цена не найдена или неоднозначна' };
    } else result = { ok: false, error: 'Неизвестное действие' };
  } catch (error) {
    console.error(error);
    result = { ok: false, error: 'Не удалось прочитать базу цен' };
  }
  return ContentService.createTextOutput(callback
    ? callback + '(' + JSON.stringify(result) + ');'
    : JSON.stringify(result))
    .setMimeType(callback ? ContentService.MimeType.JAVASCRIPT : ContentService.MimeType.JSON);
}

/** Form POST keeps the customer's name and phone out of URLs and browser history. */
function doPost(e) {
  var p = (e && e.parameter) || {};
  var nonce = String(p.nonce || '');
  var result = { source: 'gts-booking', nonce: /^[a-zA-Z0-9_]{12,100}$/.test(nonce) ? nonce : '', ok: false };
  try {
    if (p.action !== 'lead' || !result.nonce || p.website || p.consent !== 'yes') throw new Error('Invalid form');
    var name = String(p.name || '').trim().replace(/\s+/g, ' ');
    if (name.length < 2 || name.length > 80 || !/^[\p{L}][\p{L}\s.'-]*$/u.test(name)) throw new Error('Invalid name');
    var phone = normalizePhone_(p.phone);
    if (!phone) throw new Error('Invalid phone');
    var db = readDatabase_();
    var match = db.prices.filter(function(row) {
      return row.modelId === p.modelId && row.type === p.type && row.priceId === p.priceId;
    });
    var car = db.models.filter(function(row) { return row.modelId === p.modelId; });
    if (match.length !== 1 || car.length !== 1) throw new Error('Invalid quote');
    var credentials = PropertiesService.getScriptProperties();
    var token = credentials.getProperty('TELEGRAM_BOT_TOKEN');
    var chatId = credentials.getProperty('TELEGRAM_CHAT_ID');
    if (!token || !chatId) throw new Error('Telegram is not configured');
    var cache = CacheService.getScriptCache();
    if (cache.get('lead-' + result.nonce)) { result.ok = true; return leadResponse_(result); }
    var message = [
      'Новая заявка на ТО',
      'Имя: ' + name,
      'Телефон: ' + phone,
      'Автомобиль: ' + car[0].brand + ' ' + car[0].model + ' — ' + car[0].variant,
      'Услуга: ' + match[0].type,
      'Стоимость: ' + match[0].price + ' ₽',
      'ID цены: ' + match[0].priceId,
      'Согласие на обработку данных: да'
    ].join('\n');
    var response = UrlFetchApp.fetch('https://api.telegram.org/bot' + token + '/sendMessage', {
      method: 'post', contentType: 'application/json',
      payload: JSON.stringify({ chat_id: chatId, text: message }),
      muteHttpExceptions: true
    });
    if (response.getResponseCode() !== 200 || !JSON.parse(response.getContentText()).ok) throw new Error('Telegram send failed');
    cache.put('lead-' + result.nonce, 'sent', 600);
    result.ok = true;
  } catch (error) {
    // Do not log names, phone numbers or the Telegram token.
    console.error('Lead delivery failed');
  }
  return leadResponse_(result);
}

function normalizePhone_(value) {
  var digits = String(value || '').replace(/\D/g, '');
  if (digits.length === 10 && digits.charAt(0) === '9') digits = '7' + digits;
  if (digits.length === 11 && digits.charAt(0) === '8') digits = '7' + digits.slice(1);
  return /^7\d{10}$/.test(digits) ? '+' + digits : '';
}

function leadResponse_(result) {
  // The POST targets a hidden iframe. Its HTML sends only the outcome and
  // request nonce to the enclosing site; the visitor's details stay server-side.
  var html = '<!doctype html><meta charset="utf-8"><script>window.top.postMessage(' +
    JSON.stringify(result) + ',"*");<\/script>';
  return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function readDatabase_() {
  var cache = CacheService.getScriptCache();
  var saved = cache.get('gts-maintenance-v1');
  if (saved) return JSON.parse(saved);
  var sheet = SpreadsheetApp.getActiveSpreadsheet();
  var modelsSheet = sheet.getSheetByName('Лист1');
  var pricesSheet = sheet.getSheetByName('Лист2');
  if (!modelsSheet || !pricesSheet) throw new Error('Missing Лист1 or Лист2');
  var modelData = modelsSheet.getDataRange().getValues();
  var priceData = pricesSheet.getDataRange().getValues();
  var m = columns_(modelData.shift(), ['model_id','марка','модель','вариант_из_источника']);
  var c = columns_(priceData.shift(), ['price_id','model_id','вид_ТО','итого_руб','статус']);
  var byId = Object.create(null);
  modelData.forEach(function(row) {
    var id = String(row[m.model_id] || '').trim();
    if (!id) return;
    if (byId[id]) throw new Error('Duplicate model_id: ' + id);
    byId[id] = { modelId: id, brand: String(row[m['марка']] || '').trim(),
      model: String(row[m['модель']] || '').trim(),
      variant: String(row[m['вариант_из_источника']] || '').trim(), types: [] };
  });
  var byPriceId = Object.create(null), byKey = Object.create(null);
  var prices = [];
  priceData.forEach(function(row) {
    if (String(row[c['статус']] || '').trim().toLowerCase() !== 'готово') return;
    var priceId = String(row[c.price_id] || '').trim();
    var modelId = String(row[c.model_id] || '').trim();
    var type = String(row[c['вид_ТО']] || '').trim();
    var rawPrice = row[c['итого_руб']];
    var price = typeof rawPrice === 'number' ? rawPrice
      : Number(String(rawPrice).replace(/[\s\u00a0\u202f]/g, '').replace(',', '.'));
    if (!priceId || !byId[modelId] || !type || !Number.isFinite(price) || price < 0) return;
    if (byPriceId[priceId]) throw new Error('Duplicate price_id: ' + priceId);
    byPriceId[priceId] = true;
    var key = modelId + '\u0000' + type;
    byKey[key] = (byKey[key] || 0) + 1;
    prices.push({ priceId: priceId, modelId: modelId, type: type, price: price });
  });
  // Omit ambiguous vehicle labels and duplicate model/type prices entirely.
  var labelCounts = Object.create(null);
  Object.keys(byId).forEach(function(id) {
    var row = byId[id];
    var key = [row.brand,row.model,row.variant].join('\u0000');
    labelCounts[key] = (labelCounts[key] || 0) + 1;
  });
  var validIds = Object.create(null);
  var models = Object.keys(byId).map(function(id) { return byId[id]; }).filter(function(row) {
    var unique = labelCounts[[row.brand,row.model,row.variant].join('\u0000')] === 1;
    if (unique && row.brand && row.model && row.variant) validIds[row.modelId] = true;
    return unique && row.brand && row.model && row.variant;
  });
  prices = prices.filter(function(row) {
    return validIds[row.modelId] && byKey[row.modelId + '\u0000' + row.type] === 1;
  });
  prices.forEach(function(row) { byId[row.modelId].types.push(row.type); });
  models = models.filter(function(row) { return row.types.length > 0; });
  var db = { models: models, prices: prices };
  var json = JSON.stringify(db);
  if (json.length < 90000) cache.put('gts-maintenance-v1', json, 300);
  return db;
}

function columns_(header, required) {
  var positions = Object.create(null);
  header.forEach(function(value, i) { positions[String(value).trim()] = i; });
  required.forEach(function(name) {
    if (!Object.prototype.hasOwnProperty.call(positions, name)) throw new Error('Missing column: ' + name);
  });
  return positions;
}
