/** Web app bound to the price spreadsheet (Extensions → Apps Script). */
var GTS_API_VERSION = '2026-09-26.3';
function doGet(e) {
  var p = (e && e.parameter) || {};
  var callback = p.callback || '';
  // JSONP callback names are generated by the site and never taken verbatim.
  if (callback && !/^__gtsToCallback_[A-Za-z0-9_]+$/.test(callback)) {
    return ContentService.createTextOutput('Invalid callback').setMimeType(ContentService.MimeType.TEXT);
  }
  var result;
  try {
    if (p.action === 'version') result = { ok: true, version: GTS_API_VERSION };
    else if (p.action === 'leadStatus') {
      var requestNonce = String(p.nonce || '');
      if (!/^[a-zA-Z0-9_]{12,100}$/.test(requestNonce)) {
        result = { ok: false, error: 'Invalid request' };
      } else {
        result = { ok: true, status: CacheService.getScriptCache().get('lead-' + requestNonce) === 'sent' ? 'sent' : 'pending' };
      }
    }
    else if (p.action === 'offers') result = { ok: true, offers: readOffers_(false) };
    else if (p.action === 'catalog') result = { ok: true, models: readDatabase_().models };
    else if (p.action === 'quote') {
      var db = readDatabase_();
      var match = db.prices.filter(function(row) {
        return row.modelId === p.modelId && row.type === p.type;
      });
      result = match.length === 1
        ? { ok: true, modelId: match[0].modelId, type: match[0].type,
            priceId: match[0].priceId, price: match[0].price, currency: 'RUB' }
        : { ok: false, error: 'Цена не найдена или неоднозначна' };
    } else result = { ok: false, error: 'Неизвестное действие' };
  } catch (error) {
    console.error(error);
    // Report only expected sheet setup errors; do not expose server details.
    var setupError = String(error && error.message || '');
    result = { ok: false, error: p.action === 'offers' &&
      /^(Missing promotion sheet: |Missing column: )/.test(setupError)
        ? setupError.replace('Missing promotion sheet: ', 'Не найден лист: ')
          .replace('Missing column: ', 'Не найден столбец: ')
        : 'Не удалось прочитать базу цен' };
  }
  return ContentService.createTextOutput(callback
    ? callback + '(' + JSON.stringify(result) + ');'
    : JSON.stringify(result))
    .setMimeType(callback ? ContentService.MimeType.JAVASCRIPT : ContentService.MimeType.JSON);
}

/** Form POST keeps the customer's name and phone out of URLs and browser history. */
function doPost(e) {
  var p = (e && e.parameter) || {};
  var nonce = String(p.nonce || '');
  var result = { source: 'gts-booking', version: GTS_API_VERSION,
    nonce: /^[a-zA-Z0-9_]{12,100}$/.test(nonce) ? nonce : '', ok: false };
  try {
    result.code = 'INVALID_FORM';
    if (p.action !== 'lead' || !result.nonce || p.website || p.consent !== 'yes') throw new Error('Invalid form');
    var name = String(p.name || '').trim().replace(/\s+/g, ' ');
    result.code = 'INVALID_NAME';
    if (name.length < 2 || name.length > 80 || !/^[\p{L}][\p{L}\s.'-]*$/u.test(name)) throw new Error('Invalid name');
    var phone = normalizePhone_(p.phone);
    result.code = 'INVALID_PHONE';
    if (!phone) throw new Error('Invalid phone');
    var messageLines;
    if (p.kind === 'callback') {
      messageLines = ['Заказ обратного звонка', 'Имя: ' + name, 'Телефон: ' + phone];
    } else if (p.kind === 'custom') {
      result.code = 'INVALID_REQUEST';
      var request = String(p.request || '').trim();
      if (!request || request.length > 1000) throw new Error('Invalid custom request');
      messageLines = ['Новая заявка: автомобиля нет в списке', 'Имя: ' + name,
        'Телефон: ' + phone, 'Запрос: ' + request];
    } else if (p.kind === 'offer') {
      // For a lead, read the sheet again: disabling an offer must take effect
      // immediately even if the public card list is still cached.
      result.code = 'OFFER_READ_FAILED';
      var offer = readOffers_(true).filter(function(row) { return row.offerId === p.offerId; });
      if (offer.length !== 1) {
        result.code = 'OFFER_UNAVAILABLE';
        throw new Error('Inactive or unknown offer');
      }
      if (p.expectedPrice === undefined || p.expectedPrice === '' || !Number.isFinite(Number(p.expectedPrice)) || Number(p.expectedPrice) !== offer[0].price) {
        result.code = 'PRICE_CHANGED';
        throw new Error('Offer price changed');
      }
      messageLines = ['Новая заявка по акции', 'Имя: ' + name, 'Телефон: ' + phone,
        'Акция: ' + offer[0].title, 'Стоимость: ' + offer[0].price + ' ₽',
        'ID акции: ' + offer[0].offerId];
    } else if (p.kind === 'maintenance' || !p.kind) {
      result.code = 'MAINTENANCE_READ_FAILED';
      var db = readDatabase_();
      var match = db.prices.filter(function(row) {
        return row.modelId === p.modelId && row.type === p.type && row.priceId === p.priceId;
      });
      var car = db.models.filter(function(row) { return row.modelId === p.modelId; });
      if (match.length !== 1 || car.length !== 1) {
        result.code = 'INVALID_QUOTE';
        throw new Error('Invalid quote');
      }
      messageLines = ['Новая заявка на ТО', 'Имя: ' + name, 'Телефон: ' + phone,
        'Автомобиль: ' + car[0].brand + ' ' + car[0].model + ' — ' + car[0].variant,
        'Услуга: ' + match[0].type, 'Стоимость: ' + match[0].price + ' ₽',
        'ID цены: ' + match[0].priceId];
    } else {
      result.code = 'INVALID_KIND';
      throw new Error('Unknown lead kind');
    }
    result.code = 'PROPERTIES_UNAVAILABLE';
    var credentials = PropertiesService.getScriptProperties();
    var token = String(credentials.getProperty('TELEGRAM_BOT_TOKEN') || '').trim();
    var chatId = String(credentials.getProperty('TELEGRAM_CHAT_ID') || '').trim();
    if (!token || !chatId) {
      result.code = 'TELEGRAM_NOT_CONFIGURED';
      throw new Error('Telegram is not configured');
    }
    result.code = 'CACHE_UNAVAILABLE';
    var cache = CacheService.getScriptCache();
    if (cache.get('lead-' + result.nonce)) {
      result.ok = true;
      delete result.code;
      return leadResponse_(result);
    }
    var message = messageLines.concat('Согласие на обработку данных: да').join('\n');
    result.code = 'TELEGRAM_REQUEST_FAILED';
    var response = UrlFetchApp.fetch('https://api.telegram.org/bot' + token + '/sendMessage', {
      method: 'post', contentType: 'application/json',
      payload: JSON.stringify({ chat_id: chatId, text: message }),
      muteHttpExceptions: true
    });
    var status = response.getResponseCode();
    if (status !== 200) {
      result.code = status === 401 || status === 404 ? 'TELEGRAM_BAD_TOKEN'
        : status === 400 || status === 403 ? 'TELEGRAM_BAD_CHAT'
        : 'TELEGRAM_SEND_FAILED';
      throw new Error('Telegram HTTP ' + status);
    }
    if (!JSON.parse(response.getContentText()).ok) {
      result.code = 'TELEGRAM_SEND_FAILED';
      throw new Error('Telegram rejected the message');
    }
    result.ok = true;
    delete result.code;
    try { cache.put('lead-' + result.nonce, 'sent', 600); }
    catch (cacheError) { console.error('Lead deduplication cache unavailable'); }
  } catch (error) {
    // Do not log names, phone numbers or the Telegram token.
    result.code = result.code || 'INTERNAL_ERROR';
    console.error('Lead delivery failed: ' + result.code);
  }
  return leadResponse_(result);
}

function readOffers_(fresh) {
  var cache = CacheService.getScriptCache();
  var saved = !fresh && cache.get('gts-offers-v1');
  if (saved) return JSON.parse(saved);
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var offersSheet = spreadsheet.getSheetByName('Акции');
  var itemsSheet = spreadsheet.getSheetByName('Состав_акций');
  if (!offersSheet) throw new Error('Missing promotion sheet: Акции');
  if (!itemsSheet) throw new Error('Missing promotion sheet: Состав_акций');
  var offerRows = offersSheet.getDataRange().getValues();
  var itemRows = itemsSheet.getDataRange().getValues();
  var o = columns_(offerRows.shift(), ['offer_id','название','цена_руб','активна','порядок']);
  var i = columns_(itemRows.shift(), ['offer_id','порядок','пункт']);
  var counts = Object.create(null), byId = Object.create(null);
  offerRows.forEach(function(row) {
    var id = String(row[o.offer_id] || '').trim();
    if (id) counts[id] = (counts[id] || 0) + 1;
  });
  offerRows.forEach(function(row) {
    var id = String(row[o.offer_id] || '').trim();
    var title = String(row[o['название']] || '').trim();
    var raw = row[o['цена_руб']];
    var price = typeof raw === 'number' ? raw : Number(String(raw).replace(/[\s\u00a0\u202f]/g, '').replace(',', '.'));
    // An unchecked checkbox is boolean false. Text "TRUE" is not an active marker.
    if (!id || counts[id] !== 1 || row[o['активна']] !== true || !title || raw === '' || raw === null || !Number.isFinite(price) || price < 0) return;
    byId[id] = { offerId: id, title: title, price: price,
      order: Number(row[o['порядок']]) || 9999, items: [] };
  });
  itemRows.forEach(function(row) {
    var item = byId[String(row[i.offer_id] || '').trim()];
    var text = String(row[i['пункт']] || '').trim();
    if (item && text) item.items.push({ order: Number(row[i['порядок']]) || 9999, text: text });
  });
  var offers = Object.keys(byId).map(function(id) { return byId[id]; });
  offers.forEach(function(offer) {
    offer.items.sort(function(a,b) { return a.order - b.order; });
    offer.items = offer.items.map(function(item) { return item.text; });
  });
  offers.sort(function(a,b) { return a.order - b.order || a.offerId.localeCompare(b.offerId); });
  offers.forEach(function(offer) { delete offer.order; });
  if (!fresh) cache.put('gts-offers-v1', JSON.stringify(offers), 60);
  return offers;
}

function normalizePhone_(value) {
  var digits = String(value || '').replace(/\D/g, '');
  if (digits.length === 10 && digits.charAt(0) === '9') digits = '7' + digits;
  if (digits.length === 11 && digits.charAt(0) === '8') digits = '7' + digits.slice(1);
  return /^7\d{10}$/.test(digits) ? '+' + digits : '';
}

function leadResponse_(result) {
  // The POST targets a hidden iframe. Its HTML sends only the outcome and
  // request nonce to the enclosing site; the visitor's details stay server-side.
  var html = '<!doctype html><meta charset="utf-8"><script>window.top.postMessage(' +
    JSON.stringify(result) + ',"*");<\/script>';
  return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function readDatabase_() {
  var cache = CacheService.getScriptCache();
  var saved = cache.get('gts-maintenance-v1');
  if (saved) return JSON.parse(saved);
  var sheet = SpreadsheetApp.getActiveSpreadsheet();
  var modelsSheet = sheet.getSheetByName('Лист1');
  var pricesSheet = sheet.getSheetByName('Лист2');
  if (!modelsSheet || !pricesSheet) throw new Error('Missing Лист1 or Лист2');
  var modelData = modelsSheet.getDataRange().getValues();
  var priceData = pricesSheet.getDataRange().getValues();
  var m = columns_(modelData.shift(), ['model_id','марка','модель','вариант_из_источника']);
  var c = columns_(priceData.shift(), ['price_id','model_id','вид_ТО','итого_руб','статус']);
  var byId = Object.create(null);
  modelData.forEach(function(row) {
    var id = String(row[m.model_id] || '').trim();
    if (!id) return;
    if (byId[id]) throw new Error('Duplicate model_id: ' + id);
    byId[id] = { modelId: id, brand: String(row[m['марка']] || '').trim(),
      model: String(row[m['модель']] || '').trim(),
      variant: String(row[m['вариант_из_источника']] || '').trim(), types: [] };
  });
  var byPriceId = Object.create(null), byKey = Object.create(null);
  var prices = [];
  priceData.forEach(function(row) {
    if (String(row[c['статус']] || '').trim().toLowerCase() !== 'готово') return;
    var priceId = String(row[c.price_id] || '').trim();
    var modelId = String(row[c.model_id] || '').trim();
    var type = String(row[c['вид_ТО']] || '').trim();
    var rawPrice = row[c['итого_руб']];
    var price = typeof rawPrice === 'number' ? rawPrice
      : Number(String(rawPrice).replace(/[\s\u00a0\u202f]/g, '').replace(',', '.'));
    if (!priceId || !byId[modelId] || !type || !Number.isFinite(price) || price < 0) return;
    if (byPriceId[priceId]) throw new Error('Duplicate price_id: ' + priceId);
    byPriceId[priceId] = true;
    var key = modelId + '\u0000' + type;
    byKey[key] = (byKey[key] || 0) + 1;
    prices.push({ priceId: priceId, modelId: modelId, type: type, price: price });
  });
  // Omit ambiguous vehicle labels and duplicate model/type prices entirely.
  var labelCounts = Object.create(null);
  Object.keys(byId).forEach(function(id) {
    var row = byId[id];
    var key = [row.brand,row.model,row.variant].join('\u0000');
    labelCounts[key] = (labelCounts[key] || 0) + 1;
  });
  var validIds = Object.create(null);
  var models = Object.keys(byId).map(function(id) { return byId[id]; }).filter(function(row) {
    var unique = labelCounts[[row.brand,row.model,row.variant].join('\u0000')] === 1;
    if (unique && row.brand && row.model && row.variant) validIds[row.modelId] = true;
    return unique && row.brand && row.model && row.variant;
  });
  prices = prices.filter(function(row) {
    return validIds[row.modelId] && byKey[row.modelId + '\u0000' + row.type] === 1;
  });
  prices.forEach(function(row) { byId[row.modelId].types.push(row.type); });
  models = models.filter(function(row) { return row.types.length > 0; });
  var db = { models: models, prices: prices };
  var json = JSON.stringify(db);
  if (json.length < 90000) cache.put('gts-maintenance-v1', json, 300);
  return db;
}

function columns_(header, required) {
  var positions = Object.create(null);
  header.forEach(function(value, i) { positions[String(value).trim()] = i; });
  required.forEach(function(name) {
    if (!Object.prototype.hasOwnProperty.call(positions, name)) throw new Error('Missing column: ' + name);
  });
  return positions;
}
