// Generated by npm run build. Edit data.js and app.js instead.
(() => {
"use strict";
// Данные и контакты редактируются здесь, независимо от оформления.
// Не публикуйте тестовый телефон и неподтверждённый номер дома.
const config = {
  phone: '', // Международный формат: +7…
  telegram: '', // Полная ссылка https://t.me/…
  address: 'Нижний Новгород, Московское шоссе',
  house: '', // В исходнике расходятся 52б и 52д — требуется подтверждение.
  hours: '', // Подтвердить режим из наброска: ежедневно 09:00–21:00.
  heroVideo: './assets/service_zone.mp4', // Локальный путь, например ./assets/hero.mp4.
};
const prices = {
  Hyundai: { Solaris: 12000, Tucson: 13000, 'Santa Fe': 18000 },
  Kia: { Rio: 11500, K5: 13500, Sorento: 17500 },
  Genesis: { G70: 17000, G80: 25000, G90: 35000 },
};
const services = [
  { title: 'Техническое обслуживание', text: 'Плановое обслуживание по регламенту автомобиля. Масло, фильтры и необходимые проверки.', action: 'Записаться', target: '#contacts', icon: '01' },
  { title: 'Ремонт автомобиля', text: 'От отдельных узлов до сложного ремонта агрегатов. Начнём с уточнения задачи.', action: 'Записаться', target: '#contacts', icon: '02' },
  { title: 'Диагностика', text: 'Проверка двигателя, ходовой части и других систем. Поиск причины неисправности.', action: 'Записаться', target: '#contacts', icon: '03' },
  { title: 'Детейлинг и доработки', text: 'Полировка, химчистка, защитная плёнка и другие работы по уходу за автомобилем.', action: 'Записаться', target: '#contacts', icon: '04' },
];
const offers = [
  { title: 'Диагностика двигателя', price: 2999, items: ['Компьютерная диагностика', 'Замер компрессии и эндоскопия', 'Проверка навесного оборудования', 'Осмотр на предмет течей'] },
  { title: 'Диагностика ходовой', price: 999, items: ['Проверка амортизаторов', 'Осмотр тормозной системы', 'Проверка люфтов', 'Осмотр резинотехнических деталей'] },
  { title: 'Диагностика кондиционера', price: 3999, items: ['Проверка эффективности охлаждения', 'Проверка уровня хладагента', 'Осмотр испарителя и конденсора'] },
];
const team = [
  { name: 'Тимофей Дмитриев', role: 'Руководитель ремонтного цеха', image: 'timofey.jpg', photos: [{ kind: 'portrait', alt: 'Портрет — заглушка' }, { kind: 'certificate', alt: 'Сертификат — заглушка' }], text: 'Диагностика, технические вопросы и организация ремонта.' },
  { name: 'Владислав Матросов', role: 'Директор сервиса', image: 'vladislav.jpg', photos: [{ kind: 'portrait', alt: 'Портрет — заглушка' }, { kind: 'certificate', alt: 'Сертификат — заглушка' }], text: 'Организация работы команды и клиентский сервис.' },
  { name: 'Вадим Смирнов', role: 'Старший сервисный консультант', image: 'vadim.jpg', photos: [{ kind: 'portrait', alt: 'Портрет — заглушка' }, { kind: 'certificate', alt: 'Сертификат — заглушка' }], text: 'Обсуждение задач и сопровождение обслуживания.' },
];
function getPrice(brand, model) {
  return Object.hasOwn(prices, brand) && Object.hasOwn(prices[brand], model) ? prices[brand][model] : null;
}

// Альбомы пространства сервиса. Добавляйте любое количество { src, alt }.
// Новые снимки клиентской и ремонтной зон пока не предоставлены.
const spaceAlbums = [
  [
    { src: './assets/exterior.jpg', alt: 'Фасад сервисного центра' },
    { src: './assets/workshop.png', alt: 'Ремонтная зона сервисного центра' },
    { src: './assets/lounge.jpg', alt: 'Клиентская зона сервисного центра' },
  ],
  [{ src: './assets/lounge.jpg', alt: 'Клиентская зона' }],
  [{ src: './assets/workshop.png', alt: 'Ремонтная зона' }],
];

const $ = (selector) => document.querySelector(selector);
const money = (value) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(value);
const escape = (value) => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
$('#services-list').innerHTML = services.map((s, i) => `<article class="service-card"><div class="service-card-head"><span class="card-number">${s.icon} /</span><button class="service-toggle" type="button" aria-expanded="false" aria-controls="service-panel-${i}" aria-label="Открыть описание: ${escape(s.title)}"></button></div><h3>${escape(s.title)}</h3><div class="service-details" id="service-panel-${i}" hidden><p>${escape(s.text)}</p><button class="service-action button light-button" type="button">${escape(s.action)}</button></div></article>`).join('');
$('#offers-list').innerHTML = offers.map((s, i) => `<article class="offer-card"><span class="card-number">0${i + 1} /</span><h3>${escape(s.title)}</h3><strong>${money(s.price)}</strong><ul>${s.items.map(item => `<li>${escape(item)}</li>`).join('')}</ul><button class="service-action button light-button" type="button">Записаться</button></article>`).join('');
$('#team-list').innerHTML = team.map(s => `<article class="team-card"><img src="./assets/${escape(s.image)}" alt="Временное фото для карточки: ${escape(s.name)}" loading="lazy"><p class="team-role">${escape(s.role)}</p><h3>${escape(s.name)}</h3><p>${escape(s.text)}</p></article>`).join('');
const brand = $('#brand'), model = $('#model');
Object.keys(prices).forEach(name => brand.add(new Option(name, name)));
function updatePrice() {
  const value = getPrice(brand.value, model.value);
  $('#price').textContent = value === null ? '—' : money(value);
  $('#price-note').textContent = value === null ? 'Выберите ваш автомобиль' : `${brand.value} ${model.value} · предварительный расчёт`;
}
brand.addEventListener('change', () => {
  model.replaceChildren(new Option(brand.value ? 'Выберите модель' : 'Сначала выберите марку', ''));
  model.disabled = !brand.value;
  if (brand.value) Object.keys(prices[brand.value]).forEach(name => model.add(new Option(name, name)));
  updatePrice();
});
model.addEventListener('change', updatePrice);
$('#calculator-form').addEventListener('submit', event => {
  event.preventDefault();
});
const serviceCards = [...document.querySelectorAll('.service-card')];
function closeServiceCard(card) {
  const button = card.querySelector('.service-toggle');
  const details = card.querySelector('.service-details');
  if (!button || !details) return;
  card.classList.remove('is-open');
  button.setAttribute('aria-expanded', 'false');
  button.setAttribute('aria-label', `Открыть описание: ${card.querySelector('h3')?.textContent || 'услуга'}`);
  details.hidden = true;
}
serviceCards.forEach((card) => {
  const button = card.querySelector('.service-toggle');
  const details = card.querySelector('.service-details');
  if (!button || !details) return;
  button.addEventListener('click', () => {
    const willOpen = button.getAttribute('aria-expanded') !== 'true';
    serviceCards.forEach(item => closeServiceCard(item));
    if (!willOpen) return;
    card.classList.add('is-open');
    button.setAttribute('aria-expanded', 'true');
    button.setAttribute('aria-label', `Закрыть описание: ${card.querySelector('h3')?.textContent || 'услуга'}`);
    details.hidden = false;
  });
});
const menuButton = $('.menu-toggle'), navigation = $('#navigation');
function closeMenu() {
  menuButton.setAttribute('aria-expanded', 'false');
  navigation.classList.remove('is-open');
  document.body.classList.remove('menu-open');
}
menuButton.addEventListener('click', () => {
  const open = menuButton.getAttribute('aria-expanded') !== 'true';
  menuButton.setAttribute('aria-expanded', String(open));
  navigation.classList.toggle('is-open', open);
  document.body.classList.toggle('menu-open', open);
});
navigation.querySelectorAll('a').forEach(a => a.addEventListener('click', closeMenu));
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeMenu(); });
document.addEventListener('click', event => {
  if (!document.body.classList.contains('menu-open')) return;
  if (navigation.contains(event.target) || menuButton.contains(event.target)) return;
  closeMenu();
});
const contactLinks = [];
if (/^\+[1-9]\d{7,14}$/.test(config.phone)) contactLinks.push({href: `tel:${config.phone}`, text: config.phone});
if (/^https:\/\/t\.me\/[a-zA-Z0-9_]+$/.test(config.telegram)) contactLinks.push({href: config.telegram, text: 'Написать в Telegram'});
for (const item of contactLinks) { const a = document.createElement('a'); a.className = 'button primary'; a.href = item.href; a.textContent = item.text; $('#contact-actions').append(a); }
if (contactLinks.length) $('#contact-status').textContent = 'Свяжитесь с нами, чтобы уточнить стоимость и время визита.';
$('.contact-card > p').textContent = [config.address, config.house, config.hours].filter(Boolean).join(' · ');
$('#year').textContent = new Date().getFullYear();
if (config.heroVideo && !matchMedia('(prefers-reduced-motion: reduce)').matches) {
  const video = $('.hero-video'); video.src = config.heroVideo;
  video.addEventListener('playing', () => { video.hidden = false; });
  video.play().catch(() => { video.hidden = true; });
}


function revealLetters(element) {
  const text = element.dataset.typeText || element.textContent.trim();
  if (!text || element.dataset.typed === 'true') return;
  element.dataset.typed = 'true';
  element.dataset.typeText = text;
  let letterIndex = 0;
  element.replaceChildren(...[...text].map((char) => {
    if (/\s/.test(char)) return document.createTextNode(char);
    const span = document.createElement('span');
    span.textContent = char;
    span.className = 'letter-reveal';
    span.style.setProperty('--letter-delay', `${letterIndex * 18}ms`);
    letterIndex += 1;
    return span;
  }));
  element.classList.add('is-typed');
}

function setupRevealAnimations() {
  const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const animatedBlocks = [
    { root: $('.hero'), items: ['.eyebrow', 'h1', '.hero-description', '.actions .button', '.hero-bottom'] },
    { root: $('#services'), items: ['.section-heading .eyebrow', '.section-heading h2', '.section-heading > p', '.service-card'] },
    { root: $('#calculator'), items: ['.eyebrow', 'h2', '.section-description', '.fine-print', '.calculator-card'] },
    { root: $('#offers'), items: ['.section-heading .eyebrow', '.section-heading h2', '.section-heading > p', '.fine-print'] },
    { root: $('#space'), items: ['.section-heading .eyebrow', '.section-heading h2', '.section-heading > p'] },
    { root: $('#team'), items: ['.section-heading .eyebrow', '.section-heading h2', '.section-heading > p'] },
  ].filter(block => block.root);

  document.documentElement.classList.add('animate-ready');

  animatedBlocks.forEach((block) => {
    let order = 0;
    block.items.forEach((selector) => {
      block.root.querySelectorAll(selector).forEach((element) => {
        element.classList.add('reveal-item');
        element.style.setProperty('--reveal-delay', `${Math.min(order * 90, 540)}ms`);
        order += 1;
      });
    });
    block.root.querySelectorAll('h1, h2').forEach(element => element.classList.add('reveal-heading'));
    block.root.querySelectorAll('.hero-description, .section-heading > p, .section-description').forEach(element => {
      element.classList.add('typewriter-text');
      element.dataset.typeText = element.textContent.trim();
      element.style.minHeight = `${element.offsetHeight}px`;
    });
  });

  if (reduceMotion) {
    document.querySelectorAll('.reveal-item').forEach(element => element.classList.add('is-visible'));
    document.querySelectorAll('.typewriter-text').forEach(element => element.classList.add('is-typed'));
    return;
  }

  const revealObserver = new IntersectionObserver((entries, observer) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add('is-visible');
      if (entry.target.classList.contains('typewriter-text')) revealLetters(entry.target);
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.18, rootMargin: '0px 0px -10% 0px' });

  document.querySelectorAll('.reveal-item').forEach(element => revealObserver.observe(element));
}

setupRevealAnimations();

function setupMobileCardProgress() {
  const blocks = [
    { section: $('#offers'), scroller: $('#offers-list') },
    { section: $('#space'), scroller: document.querySelector('#space .space-grid') },
    { section: $('#team'), scroller: $('#team-list') },
  ].filter(item => item.section && item.scroller);

  blocks.forEach(({ section, scroller }) => {
    scroller.classList.add('mobile-card-scroll');
    const progress = document.createElement('div');
    progress.className = 'mobile-scroll-progress';
    progress.innerHTML = '<span></span>';
    section.append(progress);
    const bar = progress.querySelector('span');
    const update = () => {
      const total = Math.max(scroller.scrollWidth, 1);
      const value = scroller.scrollWidth <= scroller.clientWidth ? 1 : Math.min((scroller.scrollLeft + scroller.clientWidth) / total, 1);
      bar.style.transform = `scaleX(${Number.isFinite(value) ? value : 0})`;
      const scrollerRect = scroller.getBoundingClientRect();
      const activePoint = scrollerRect.left;
      [...scroller.children].forEach((card) => {
        const cardRect = card.getBoundingClientRect();
        const distance = Math.abs(cardRect.left - activePoint);
        const fadeRange = Math.max(cardRect.width * .55, 1);
        const opacity = Math.max(.6, 1 - (distance / fadeRange) * .4);
        card.style.setProperty('--scroll-card-opacity', opacity.toFixed(3));
      });
    };
    scroller.addEventListener('scroll', update, { passive: true });
    window.addEventListener('resize', update);
    update();
  });
}

setupMobileCardProgress();

const contactWidget = $('.contact-widget');
if (contactWidget) {
  const contactButton = contactWidget.querySelector('.contact-widget-toggle');
  contactButton.addEventListener('click', () => {
    const open = contactButton.getAttribute('aria-expanded') !== 'true';
    contactButton.setAttribute('aria-expanded', String(open));
    contactWidget.classList.toggle('is-open', open);
  });
  document.addEventListener('click', (event) => {
    if (!contactWidget.classList.contains('is-open')) return;
    if (contactWidget.contains(event.target)) return;
    contactButton.setAttribute('aria-expanded', 'false');
    contactWidget.classList.remove('is-open');
  });
  document.addEventListener('keydown', (event) => {
    if (event.key !== 'Escape') return;
    contactButton.setAttribute('aria-expanded', 'false');
    contactWidget.classList.remove('is-open');
  });
}

// Общий просмотрщик; native dialog удерживает фокус внутри и поддерживает Escape.
const photoViewer = document.createElement('dialog');
photoViewer.className = 'photo-viewer';
photoViewer.setAttribute('aria-label', 'Просмотр фотографий');
photoViewer.innerHTML = `<div class="viewer-shell"><header class="viewer-header"><p class="viewer-title" aria-live="polite"></p><button class="viewer-close" type="button" aria-label="Закрыть просмотр">✕</button></header><div class="viewer-image"></div><footer class="viewer-footer"><button class="viewer-prev" type="button" aria-label="Предыдущее фото">←</button><span class="viewer-counter" aria-live="polite"></span><button class="viewer-next" type="button" aria-label="Следующее фото">→</button></footer></div>`;
document.body.append(photoViewer);
let activeAlbum = null;
let previousOverflow = '';
let viewerTrigger = null;
function updateViewer() {
  if (!activeAlbum) return;
  const { images, photos, index, title } = activeAlbum;
  const image = images[index].cloneNode(true);
  image.hidden = false;
  if (image.tagName === 'IMG') image.loading = 'eager';
  photoViewer.querySelector('.viewer-image').replaceChildren(image);
  photoViewer.querySelector('.viewer-title').textContent = `${title} · ${photos[index].alt}`;
  photoViewer.querySelector('.viewer-counter').textContent = `${index + 1} / ${images.length}`;
  photoViewer.querySelector('.viewer-prev').disabled = images.length < 2;
  photoViewer.querySelector('.viewer-next').disabled = images.length < 2;
}
function openViewer(album, trigger) {
  activeAlbum = album; viewerTrigger = trigger;
  previousOverflow = document.body.style.overflow;
  updateViewer(); photoViewer.showModal(); document.body.style.overflow = 'hidden';
  photoViewer.querySelector('.viewer-close').focus();
}
function stepViewer(direction) {
  if (!activeAlbum) return;
  activeAlbum.index = (activeAlbum.index + direction + activeAlbum.images.length) % activeAlbum.images.length;
  activeAlbum.show(activeAlbum.index); updateViewer();
}
photoViewer.querySelector('.viewer-close').addEventListener('click', () => photoViewer.close());
photoViewer.querySelector('.viewer-prev').addEventListener('click', () => stepViewer(-1));
photoViewer.querySelector('.viewer-next').addEventListener('click', () => stepViewer(1));
photoViewer.addEventListener('click', event => { if (event.target === photoViewer) photoViewer.close(); });
photoViewer.addEventListener('close', () => {
  document.body.style.overflow = previousOverflow;
  photoViewer.querySelector('.viewer-image').replaceChildren();
  activeAlbum = null; viewerTrigger?.focus();
});
photoViewer.addEventListener('keydown', event => {
  if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
    event.preventDefault(); stepViewer(event.key === 'ArrowRight' ? 1 : -1);
  }
});
let viewerTouch = null;
photoViewer.querySelector('.viewer-image').addEventListener('touchstart', event => {
  viewerTouch = event.touches.length === 1 ? { x: event.touches[0].clientX, y: event.touches[0].clientY } : null;
}, { passive: true });
photoViewer.querySelector('.viewer-image').addEventListener('touchend', event => {
  if (!viewerTouch) return;
  const dx = event.changedTouches[0].clientX - viewerTouch.x;
  const dy = event.changedTouches[0].clientY - viewerTouch.y;
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) stepViewer(dx < 0 ? 1 : -1);
  viewerTouch = null;
}, { passive: true });
photoViewer.querySelector('.viewer-image').addEventListener('touchcancel', () => { viewerTouch = null; });

// Каждая карточка имеет независимый альбом без автоматического перелистывания.
document.querySelectorAll('.space-card, .team-card').forEach((card) => {
  const isTeam = card.classList.contains('team-card');
  const siblings = [...card.parentElement.children];
  const albumIndex = siblings.indexOf(card);
  const photos = (isTeam ? team[albumIndex]?.photos : spaceAlbums[albumIndex]) || [];
  const original = card.querySelector('img');
  if (!photos.length || !original) return;
  const gallery = document.createElement('div');
  gallery.className = isTeam ? 'space-gallery team-gallery' : 'space-gallery';
  gallery.setAttribute('role', 'region');
  gallery.setAttribute('aria-label', `Фотоальбом: ${card.querySelector('h3').textContent}`);
  original.replaceWith(gallery);
  gallery.innerHTML = `<div class="space-slides"></div><div class="space-controls"><div class="photo-dots" role="group" aria-label="Выбор фотографии"></div></div><div class="photo-count" aria-live="polite" aria-atomic="true"></div>`;
  const slides = gallery.querySelector('.space-slides');
  const dots = gallery.querySelector('.photo-dots');
  let current = 0;
  let suppressOpenUntil = 0;
  const zoomButton = document.createElement('button');
  zoomButton.type = 'button'; zoomButton.className = 'photo-enlarge';
  zoomButton.setAttribute('aria-label', 'Увеличить фото');
  zoomButton.setAttribute('aria-haspopup', 'dialog');
  zoomButton.innerHTML = '<span>Увеличить</span>';
  gallery.append(zoomButton);
  zoomButton.addEventListener('click', () => {
    if (Date.now() < suppressOpenUntil) return;
    openViewer({ images, photos, index: current, title: card.querySelector('h3').textContent, show }, zoomButton);
  });
  const images = photos.map((photo, index) => {
    const img = document.createElement(photo.src ? 'img' : 'div');
    if (photo.src) {
      img.src = photo.src; img.alt = photo.alt; img.loading = 'lazy'; img.draggable = false;
      if (photo.kind === 'certificate') img.classList.add('certificate-image');
    } else {
      img.className = `team-placeholder ${photo.kind === 'certificate' ? 'certificate-placeholder' : 'portrait-placeholder'}`;
      img.setAttribute('role', 'img'); img.setAttribute('aria-label', photo.alt);
      img.innerHTML = photo.kind === 'certificate'
        ? '<div class="certificate-sheet"><div class="certificate-word">СЕРТИФИКАТ</div><div class="certificate-rule"></div><div class="certificate-dummy">ОБРАЗЕЦ</div><div class="certificate-lines"></div><div class="certificate-foot">Место для документа</div></div><div class="placeholder-caption">Сертификат · заглушка</div>'
        : '<div class="portrait-initials" aria-hidden="true">' + escape(card.querySelector('h3').textContent.split(' ').map(word => word[0]).join('')) + '</div><div class="placeholder-caption">Портрет · заглушка</div>';
    }
    img.hidden = index !== 0; slides.append(img);
    const dot = document.createElement('button');
    dot.type = 'button'; dot.setAttribute('aria-label', `Фото ${index + 1}: ${photo.alt}`);
    dot.addEventListener('click', () => show(index)); dots.append(dot);
    return img;
  });
  let slideAnimations = [];
  let slideRevision = 0;
  function show(index) {
    const previous = current;
    const next = (index + photos.length) % photos.length;
    const direction = index >= photos.length ? 1 : index < 0 ? -1 : Math.sign(next - previous);
    const revision = ++slideRevision;
    slideAnimations.forEach(animation => animation.cancel());
    slideAnimations = [];
    current = next;
    images.forEach((img, i) => {
      img.hidden = i !== current;
      img.setAttribute('aria-hidden', String(i !== current));
    });
    if (previous !== current && !matchMedia('(prefers-reduced-motion: reduce)').matches && typeof images[current].animate === 'function') {
      const outgoing = images[previous];
      const incoming = images[current];
      outgoing.hidden = false;
      const timing = { duration: 380, easing: 'cubic-bezier(.22,.61,.36,1)' };
      slideAnimations = [
        outgoing.animate([{ transform: 'translateX(0)' }, { transform: `translateX(${-direction * 100}%)` }], timing),
        incoming.animate([{ transform: `translateX(${direction * 100}%)` }, { transform: 'translateX(0)' }], timing),
      ];
      Promise.allSettled(slideAnimations.map(animation => animation.finished)).then(() => {
        if (revision !== slideRevision) return;
        outgoing.hidden = true;
        slideAnimations = [];
      });
    }
    [...dots.children].forEach((dot, i) => dot.setAttribute('aria-pressed', String(i === current)));
    zoomButton.setAttribute('aria-label', `Увеличить: ${photos[current].alt}`);
    gallery.querySelector('.photo-count').textContent = `${isTeam ? (photos[current].kind === 'certificate' ? 'Сертификат · ' : 'Портрет · ') : ''}${current + 1} / ${photos.length}`;
  }
  gallery.addEventListener('keydown', event => {
    if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
      event.preventDefault(); show(current + (event.key === 'ArrowRight' ? 1 : -1));
    }
  });
  let touchStart = null;
  gallery.addEventListener('touchstart', event => {
    touchStart = event.touches.length === 1 ? { x: event.touches[0].clientX, y: event.touches[0].clientY } : null;
  }, { passive: true });
  gallery.addEventListener('touchend', event => {
    if (!touchStart) return;
    const dx = event.changedTouches[0].clientX - touchStart.x;
    const dy = event.changedTouches[0].clientY - touchStart.y;
    if (Math.abs(dx) > 45 && Math.abs(dx) > Math.abs(dy)) { suppressOpenUntil = Date.now() + 500; show(current + (dx < 0 ? 1 : -1)); }
    touchStart = null;
  }, { passive: true });
  gallery.addEventListener('touchcancel', () => { touchStart = null; });
  // Desktop dragging complements touch swipes; dragging must not open the viewer.
  let mouseStart = null;
  zoomButton.addEventListener('pointerdown', event => {
    if (event.pointerType !== 'mouse' || event.button !== 0) return;
    mouseStart = { x: event.clientX, y: event.clientY };
    zoomButton.setPointerCapture(event.pointerId);
  });
  zoomButton.addEventListener('pointerup', event => {
    if (!mouseStart) return;
    const dx = event.clientX - mouseStart.x;
    const dy = event.clientY - mouseStart.y;
    if (Math.abs(dx) > 45 && Math.abs(dx) > Math.abs(dy)) {
      suppressOpenUntil = Date.now() + 500;
      show(current + (dx < 0 ? 1 : -1));
    }
    mouseStart = null;
    if (zoomButton.hasPointerCapture(event.pointerId)) zoomButton.releasePointerCapture(event.pointerId);
  });
  zoomButton.addEventListener('pointercancel', () => { mouseStart = null; });
  gallery.querySelector('.space-controls').hidden = photos.length < 2;
  gallery.querySelector('.photo-count').hidden = photos.length < 2;
  show(0);
});

})();
